In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('employee_churn_200k.csv')

In [7]:
df.head()

,EmployeeID,Age,Gender,Department,JobRole,MonthlyIncome,YearsAtCompany,JobSatisfaction,WorkLifeBalance,Overtime,PerformanceRating,DistanceFromHome,Attrition
0,1,56,Male,Marketing,Executive,117826,15,3,3,No,1,38,No
1,2,46,Male,Finance,Analyst,149792,8,3,4,No,2,33,No
2,3,32,Male,Finance,Executive,131383,33,1,3,No,3,24,No
3,4,25,Female,IT,Clerk,21222,8,4,3,Yes,1,3,No
4,5,38,Male,Finance,Analyst,71716,13,1,1,No,3,13,No

In [8]:
print(df.info())
print(df.describe())
print(df.columns)

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   EmployeeID         200000 non-null  int64
 1   Age                200000 non-null  int64
 2   Gender             200000 non-null  str
 3   Department         200000 non-null  str
 4   JobRole            200000 non-null  str
 5   MonthlyIncome      200000 non-null  int64
 6   YearsAtCompany     200000 non-null  int64
 7   JobSatisfaction    200000 non-null  int64
 8   WorkLifeBalance    200000 non-null  int64
 9   Overtime           200000 non-null  str
 10  PerformanceRating  200000 non-null  int64
 11  DistanceFromHome   200000 non-null  int64
 12  Attrition          200000 non-null  str
dtypes: int64(8), str(5)
memory usage: 19.8 MB
None
          EmployeeID            Age  MonthlyIncome  YearsAtCompany  \
count  200000.000000  200000.000000  200000.000000   200000.000000
mean   100000.500000      38.516835   79861.037845       19.453310
std     57735.171256      12.105827   40433.650965       11.549516
min         1.000000      18.000000   10000.000000        0.000000
25%     50000.750000      28.000000   44768.000000        9.000000
50%    100000.500000      39.000000   79802.000000       19.000000
75%    150000.250000      49.000000  114946.000000       29.000000
max    200000.000000      59.000000  149999.000000       39.000000

       JobSatisfaction  WorkLifeBalance  PerformanceRating  DistanceFromHome
count    200000.000000    200000.000000      200000.000000     200000.000000
mean          2.500225         2.502330           2.496730         24.979255
std           1.117482         1.117842           1.117652         14.113449
min           1.000000         1.000000           1.000000          1.000000
25%           2.000000         2.000000           1.000000         13.000000
50%           3.000000         2.000000           2.000000         25.000000
75%           3.000000         4.000000           3.000000         37.000000
max           4.000000         4.000000           4.000000         49.000000
Index(['EmployeeID', 'Age', 'Gender', 'Department', 'JobRole', 'MonthlyIncome',
       'YearsAtCompany', 'JobSatisfaction', 'WorkLifeBalance', 'Overtime',
       'PerformanceRating', 'DistanceFromHome', 'Attrition'],
      dtype='str')

In [6]:
df.head()

,EmployeeID,Age,Gender,Department,JobRole,MonthlyIncome,YearsAtCompany,JobSatisfaction,WorkLifeBalance,Overtime,PerformanceRating,DistanceFromHome,Attrition
0,1,56,Male,Marketing,Executive,117826,15,3,3,No,1,38,No
1,2,46,Male,Finance,Analyst,149792,8,3,4,No,2,33,No
2,3,32,Male,Finance,Executive,131383,33,1,3,No,3,24,No
3,4,25,Female,IT,Clerk,21222,8,4,3,Yes,1,3,No
4,5,38,Male,Finance,Analyst,71716,13,1,1,No,3,13,No

In [9]:
# fix target value
df['Attrition']=df['Attrition'].map({'Yes':1,'No':0})

In [10]:
df['Attrition'].head(10)

0    0
1    0
2    0
3    0
4    0
5    1
6    0
7    0
8    0
9    1
Name: Attrition, dtype: int64

In [ ]:
# overall attrition Rate
df['Attrition'].mean()

np.float64(0.36533)

In [ ]:
df.groupby('Overtime')['Attrition'].mean()*100
# Without overtime → only 21% attrition
# With overtime → 51% attrition 😳

# Key Insight:
# Overtime is a major driver of attrition
# Employees working overtime are more than twice as likely to leave
# Indicates burnout and poor work-life balance

# Reduce excessive overtime
# Improve workload distribution
# Promote work-life balance policies

Overtime
No     21.560825
Yes    51.512363
Name: Attrition, dtype: float64

In [15]:
df.head()

,EmployeeID,Age,Gender,Department,JobRole,MonthlyIncome,YearsAtCompany,JobSatisfaction,WorkLifeBalance,Overtime,PerformanceRating,DistanceFromHome,Attrition
0,1,56,Male,Marketing,Executive,117826,15,3,3,No,1,38,0
1,2,46,Male,Finance,Analyst,149792,8,3,4,No,2,33,0
2,3,32,Male,Finance,Executive,131383,33,1,3,No,3,24,0
3,4,25,Female,IT,Clerk,21222,8,4,3,Yes,1,3,0
4,5,38,Male,Finance,Analyst,71716,13,1,1,No,3,13,0

In [ ]:
df.groupby('JobSatisfaction')['Attrition'].mean()*100

# Employees with:
# Low satisfaction (1–2) → ~46% attrition 🚨
# High satisfaction (3–4) → ~26% attrition
# Low satisfaction employees are ~1.8x more likely to leave

#  Notice:
# Satisfaction 1 & 2 are almost same
# Satisfaction 3 & 4 are almost same

#  This means:
# Employees don’t leave gradually — they leave when they are unhappy
# Job satisfaction is a major factor influencing attrition
# Employees with low satisfaction are almost twice as likely to leave
# Improving satisfaction from low → medium has high impact

# BUSINESS RECOMMENDATION
# Focus on low satisfaction employees (1 & 2)
# Conduct employee feedback surveys
# Improve work environment & management

JobSatisfaction
1    46.829005
2    46.305478
3    26.542791
4    26.472296
Name: Attrition, dtype: float64

In [ ]:
df.groupby(['Overtime','JobSatisfaction'])['Attrition'].mean()
# No Overtime:
# Low satisfaction → ~31%
# High satisfaction → ~11%
# With Overtime:
# Low satisfaction → ~61% 
# High satisfaction → ~41% 
# Even happy employees leave if they work overtime
#  Worst Case:

#  Overtime + Low Satisfaction → 61% attrition 

# Shocking Insight:

# Even with high satisfaction (4):
# No overtime → 11%
# With overtime → 41% 

# Means:
# Overtime destroys retention

Overtime  JobSatisfaction
No        1                  0.318715
          2                  0.313368
          3                  0.115606
          4                  0.114435
Yes       1                  0.618135
          2                  0.613341
          3                  0.415442
          4                  0.414237
Name: Attrition, dtype: float64